Repository OWN-SIZE/onsize-extension, pull requests merged in 2023-02, with the labels that each got.

#36 QA반영 및 쇼핑몰 사이트 추가
  src/apis/index.tsx
  src/components/common/Header/Header.tsx
  src/components/common/SplitedButton/index.tsx
  src/components/size-option/SaveButton.tsx
  src/hooks/queries/useRedirect.ts
  src/hooks/queries/useSaveProduct.ts
  src/manifest.json
  src/pages/Background/index.ts
  src/pages/Content/productContent/index.ts
  src/pages/Content/sizeTableContent/index.ts
  src/pages/Popup/Popup.tsx
  src/pages/Popup/size-option/index.tsx
  src/states/atom.ts
Labels: FEAT, FIX

#38 나의 옷장으로 이동 시 401 에러 해결
  src/apis/index.tsx
  src/hooks/queries/useSaveProduct.ts
  src/manifest.json
  src/pages/Popup/size-recommend/index.tsx
Labels: FIX

#40 QA 반영
  src/apis/index.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/Main/index.tsx
  src/components/common/SplitedButton/index.tsx
  src/components/save-product/SizeRecommendButton.tsx
  src/components/size-option/OptionButton.tsx
  src/contants/domain.ts
  src/contants/text.ts
  src/hooks/queries/useRemoveLocalStorage.ts
  src/hooks/queries/useSizeRecommend.ts
  src/hooks/ui/useGoBackToHistory.ts
  src/hooks/ui/useTabs.tsx
  src/pages/Content/productContent/index.ts
  src/pages/Content/sizeTableContent/index.ts
  src/pages/Popup/Popup.tsx
  src/pages/Popup/cannotloadsize/index.tsx
  src/pages/Popup/first/index.tsx
  src/pages/Popup/nosize/index.tsx
  src/pages/Popup/save-product/index.tsx
  src/pages/Popup/size-compare/index.tsx
  src/pages/Popup/size-option/index.tsx
  src/pages/Popup/size-recommend/index.tsx
  src/pages/Popup/size-write/index.tsx
  src/states/atom.ts
Labels: FEAT

#42 재로그인, 새로고침, 탭 간 이동 시 익스텐션 리프레시
  src/assets/img/skeleton.svg
  src/manifest.json
  src/pages/Background/index.ts
  src/pages/Content/sizeTableContent/index.ts
  src/pages/Popup/Popup.tsx
  src/pages/Popup/save-product/index.tsx
  src/pages/Popup/size-compare/index.tsx
Labels: FEAT

#45 수동입력 사이즈 추천 및 관련 오류
  src/components/size-compare/SelfWriteCompare.tsx
  src/components/size-compare/Sizes.tsx
  src/components/size-compare/index.ts
  src/components/sizewrite/FormRow.tsx
  src/hooks/business/useForm.ts
  src/hooks/queries/useSizeCompare.ts
  src/pages/Popup/size-compare/index.tsx
  src/pages/Popup/size-write/index.tsx
  src/states/atom.ts
  src/types/inputSize/index.ts
  src/types/remote/index.ts
Labels: FIX

#44 비교 가능한 사이즈가 없어요 뷰 로직 수정
  src/assets/img/icon-inactive.png
  src/components/common/Header/Header.tsx
  src/components/common/SplitedButton/index.tsx
  src/components/size-compare/Compare.tsx
  src/components/size-compare/SelfWriteCompare.tsx
  src/components/size-compare/Sizes.tsx
  src/components/size-compare/index.ts
  src/contants/domain.ts
  src/hooks/queries/useRedirect.ts
  src/hooks/queries/useRemoveLocalStorage.ts
  src/hooks/queries/useSizeCompare.ts
  src/hooks/queries/useSizeRecommend.ts
  src/hooks/ui/useTabs.tsx
  src/manifest.json
  src/pages/Background/index.ts
  src/pages/Content/sizeTableContent/index.ts
  src/pages/Popup/Popup.tsx
  src/pages/Popup/size-compare/index.tsx
  src/pages/Popup/size-write/index.tsx
  src/states/atom.ts
  src/states/index.ts
Labels: FEAT

#49 최종 QA 반영
  src/components/common/Header/Header.tsx
  src/components/size-compare/SelfWriteCompare.tsx
  src/components/size-compare/Sizes.tsx
  src/hooks/queries/useSizeRecommend.ts
  src/pages/Background/index.ts
  src/pages/Popup/size-compare/index.tsx
  src/pages/Popup/size-write/index.tsx
  src/states/atom.ts
  src/states/index.ts
  utils/topBottomTextMapper.ts
Labels: FEAT, FIX

#50 수동입력 단면둘레 오류
  src/hooks/business/useForm.ts
  src/pages/Popup/size-write/index.tsx
Labels: FIX

#52 QA 개선 요청 사항 반영
  src/components/size-compare/SelfWriteCompare.tsx
  src/components/size-compare/Sizes.tsx
  src/hooks/queries/useSizeRecommend.ts
  src/pages/Background/index.ts
  src/pages/Popup/size-compare/index.tsx
  src/pages/Popup/size-write/index.tsx
  src/states/atom.ts
  src/states/index.ts
  utils/topBottomTextMapper.ts
Labels: FIX

#53 익스텐션 설치 페이지에서 아이콘 활성화, 사이즈 추천 로직 수정
  src/hooks/queries/useSizeRecommend.ts
  src/manifest.json
  src/pages/Background/index.ts
Labels: FIX
